### ISSUE TITLE
Remove BakerExtensions

### ISSUE THREAD

**Issue by foxor** [Antoshidza/NSprites-Foundation#13]
There are not one, but two(!) files in this project named BakerExtensions.cs.  Both contain 1 method which is called one time, and both are highly coupled to one specific baker class.  These are not helpful abstractions, they are annoyances.  Please remove them and migrate the associated code to the calling Bake method.

**Comment by Antoshidza** [comment]
There are actually 3 `BakerExtensions` classes. The reason behind that is this project is an example of what can be built on top of NSprites. Devs may often want to reconstruct baker classes I propose here. However in most cases even if you want to write your own baker class for say animation then animation authoring process still strongly restricted by animation workflow design, so I've prepared baker extensions methods to let devs easily use them here and there in whatever they want baker.
