### ISSUE TITLE
Sorting bug

### ISSUE THREAD

**Issue by FilipGaida99** [Antoshidza/NSprites-Foundation#17]
Sorting doesn't work with Packages/com.tonymax.nsprites.foundation/Graphics/Regular Render/RegularSprite_SG_Shader.shadergraph. 
Packages/com.tonymax.nsprites.foundation/Graphics/Regular Render/RegularSprite_Material.mat doesn't rendering at all when using Unity Atlas. 

Not matter how I set indexes between chassis and weapon off satellite, it only take in account Y position. Don't see source code for that except for regular shader, but im using SG one.

![image](https://github.com/Antoshidza/NSprites-Foundation/assets/43819017/64104824-59ce-4c2c-b411-2e987845e661)

**Comment by Antoshidza** [comment]
It is because I've forget to introduce that changes for shader graph. Sorry for that. Will try to fix that.
Also do you have any reason to use SG shader instead of regular one?

**Comment by FilipGaida99** [comment]
Thank you. I tried SG because regular won't work, but i have just realised it was my fault, because i hadn't noticed rednerer changed to 2D (probably in version upgrade). Now regular works, so this is not high priority

**Comment by Antoshidza** [comment]
I can't really get SG to work, because I can't change `SV_Position` as easy as I do it with regular HLSL. So I decide to exclude SG shader from NSprites-Foundation while SG is such a pain to advance usage.
